# Generated by Django 4.1.4 on 2022-12-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_mammogram_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mammogram',
            name='image',
            field=models.ImageField(upload_to='api/static/Images/upload'),
        ),
    ]
